# Generated by Django 3.0.7 on 2020-06-12 08:51

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_auto_20200612_1527'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='reference',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='reference',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
