# Generated by Django 3.0.7 on 2020-06-12 08:56

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('reference', '0003_auto_20200612_1551'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='reference',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='reference',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
