# Generated by Django 3.0.7 on 2020-06-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_auto_20200612_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='status',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='tags',
        ),
        migrations.AddField(
            model_name='reference',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
